core = 7.x
api = 2
projects[drupal][version] = "7.34"

libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.0.2/ckeditor_4.0.2_standard.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "git://github.com/woothemes/FlexSlider.git"
libraries[flexslider][directory_name] = "flexslider"
libraries[phamlp][download][type] = "git"
libraries[phamlp][download][url] = "git://github.com/codeincarnate/phamlp.git"
libraries[phamlp][directory_name] = "phamlp"
libraries[phamlp][destination] = modules/sass
projects[admin_menu] = "3.0-rc5"
projects[backup_migrate] = "2.8"
projects[ckeditor] = "1.16"
projects[context][version] = "3.6"
projects[ctools][version] = "1.5"
projects[date][version] = "2.8"
projects[diff][version] = "3.2"
projects[entity] = "1.5"
projects[entityreference] = "1.1"
projects[field_group] = "1.4"
projects[flexslider] = "2.0-alpha3"
projects[flexslider_views_slideshow] = "2.x-dev"
projects[google_analytics] = "1.4"
projects[google_books] = "1.0"
projects[google_cse] = "1.x-dev"
projects[imce] = "1.9"
projects[imce_wysiwyg] = "1.0"
projects[jcarousel][version] = "2.6"
projects[js_injector][version] = "2.1"
projects[jquery_update][version] = "2.4"
projects[kalturacuepoints][download][type] = "svn"
projects[kalturacuepoints][download][url] = "https://svn.library.cornell.edu/kalturacuepoints/trunk/module"
projects[kalturacuepoints][revision] = "HEAD"
projects[kalturacuepoints][subdir] = "custom"
projects[kalturacuepoints][type] = "module"
projects[libraries][version] = "2.2"
projects[link][version] = "1.3"
projects[linkit][version] = "2.7"
projects[mail_edit][version] = "1.0"
projects[menu_block][version] = "2.4"
projects[panels][version] = "3.3"
projects[pathauto][version] = "1.2"
projects[pathologic][version] = "2.12"
projects[prepro][version] = "1.4"
projects[redirect][version] = "1.0-rc1"
projects[references][version] = "2.1"
projects[rules][version] = "2.8"
projects[signale][type] = "theme"
projects[signale][download][type] = "git"
projects[signale][download][url] = "https://github.com/cul-it/signale-cornell-edu-theme"
projects[signale][download][branch] = "master"
projects[signale][directory_name] = "signale"
projects[simple_subscription] = "2.0-alpha1"
projects[subscriptions] = "1.1"
projects[token] = "1.5"
projects[transliteration] = "3.2"
projects[views][version] = "3.8"
projects[views_php][version] = "1.x-dev"
projects[views_slideshow][version] = "3.1"
projects[webform][version] = "3.21"
projects[zen][version] = "5.1"


;; signale stuff not installed
;; projects[cul_common][type] = "module"
;;projects[cul_common][download][type] = "svn"
;;projects[cul_common][download][url] =
	"https://svn.library.cornell.edu/cul_common/branches/drupal7b/module"
;;projects[cul_common][revision] = "HEAD"
;;projects[cul_common][subdir] = "custom"
;;projects[cul_login][type] = "module"
;;projects[cul_login][download][type] = "svn"
;;projects[cul_login][download][url] = "https://svn.library.cornell.edu/cul_login/branches/drupal7/module"
;;projects[cul_login][revision] = "HEAD"
;;projects[cul_login][subdir] = "custom"
;;projects[wysiwyg][version] = "2.2"
;;projects[sass] = "2.0"
;;projects[sassy] = "2.13"
;;libraries[phpsass][download][type] = "git"
;;libraries[phpsass][download][url] = "git://github.com/richthegeek/phpsass.git"
;;libraries[phpsass][directory_name] = "phpsass"




